return {
    Dark = {
        Name = "Dark",
        Accent = "#18181b",
        Dialog = "#161616",
        Outline = "#FFFFFF",
        Text = "#FFFFFF",
        Placeholder = "#999999",
        Background = "#101010",
        Button = "#52525b",
        Icon = "#a1a1aa",
    },
    Light = {
        Name = "Light",
        Accent = "#FFFFFF",
        Dialog = "#f4f4f5",
        Outline = "#09090b",
        Text = "#000000",
        Placeholder = "#777777",
        Background = "#e4e4e7",
        Button = "#18181b",
        Icon = "#52525b",
    },
    Rose = {
        Name = "Rose",
        Accent = "#be185d",
        Dialog = "#4c0519",
        Outline = "#fecdd3",
        Text = "#fdf2f8",
        Placeholder = "#f9a8d4",
        Background = "#1f0308",
        Button = "#e11d48",
        Icon = "#fb7185",
    },
    Plant = {
        Name = "Plant",
        Accent = "#166534",
        Dialog = "#052e16",
        Outline = "#bbf7d0",
        Text = "#f0fdf4",
        Placeholder = "#86efac",
        Background = "#0a1b0f",
        Button = "#16a34a",
        Icon = "#4ade80",
    },
    Red = {
        Name = "Red",
        Accent = "#991b1b",
        Dialog = "#450a0a",
        Outline = "#fecaca",
        Text = "#fef2f2",
        Placeholder = "#f87171",
        Background = "#1c0606",
        Button = "#dc2626",
        Icon = "#ef4444",
    },
    Indigo = {
        Name = "Indigo",
        Accent = "#3730a3",
        Dialog = "#1e1b4b",
        Outline = "#c7d2fe",
        Text = "#f1f5f9",
        Placeholder = "#a5b4fc",
        Background = "#0f0a2e",
        Button = "#4f46e5",
        Icon = "#6366f1",
    },
    Sky = {
        Name = "Sky",
        Accent = "#0369a1",
        Dialog = "#0c4a6e",
        Outline = "#bae6fd",
        Text = "#f0f9ff",
        Placeholder = "#7dd3fc",
        Background = "#041f2e",
        Button = "#0284c7",
        Icon = "#0ea5e9",
    },
    Violet = {
        Name = "Violet",
        Accent = "#6d28d9",
        Dialog = "#3c1361",
        Outline = "#ddd6fe",
        Text = "#faf5ff",
        Placeholder = "#c4b5fd",
        Background = "#1e0a3e",
        Button = "#7c3aed",
        Icon = "#8b5cf6",
    },
    Amber = {
        Name = "Amber",
        Accent = "#b45309",
        Dialog = "#451a03",
        Outline = "#fde68a",
        Text = "#fffbeb",
        Placeholder = "#fcd34d",
        Background = "#1c1003",
        Button = "#d97706",
        Icon = "#f59e0b",
    },
    Emerald = {
        Name = "Emerald",
        Accent = "#047857",
        Dialog = "#022c22",
        Outline = "#a7f3d0",
        Text = "#ecfdf5",
        Placeholder = "#6ee7b7",
        Background = "#011411",
        Button = "#059669",
        Icon = "#10b981",
    },
    Midnight = {
        Name = "Midnight",
        Accent = "#1e3a8a",
        Dialog = "#0c1e42",
        Outline = "#bfdbfe",
        Text = "#dbeafe",
        Placeholder = "#60a5fa",
        Background = "#0a0f1e",
        Button = "#2563eb",
        Icon = "#3b82f6",
    },
    Crimson = {
        Name = "Crimson",
        Accent = "#b91c1c",
        Dialog = "#450a0a",
        Outline = "#fca5a5",
        Text = "#fef2f2",
        Placeholder = "#9ca3af",
        Background = "#0c0404",
        Button = "#991b1b",
        Icon = "#dc2626",
    },
    MonokaiPro = {
        Name = "Monokai Pro",
        Accent = "#fc9867",
        Dialog = "#1e1e1e",
        Outline = "#78dce8",
        Text = "#fcfcfa",
        Placeholder = "#939293",
        Background = "#191622",
        Button = "#ab9df2",
        Icon = "#a9dc76",
    },
    CottonCandy = {
        Name = "Cotton Candy",
        Accent = "#ec4899",
        Dialog = "#2d1b3d",
        Outline = "#f9a8d4",
        Text = "#fdf2f8",
        Placeholder = "#c084fc",
        Background = "#1a0b2e",
        Button = "#d946ef",
        Icon = "#06b6d4",
    },
}